feat(RELEASE-1403): rework embargo-check task for issues
This commit reworks the managed embargo-check task for how it handles
issues in issues.redhat.com. First, it adds authentication for searching
for these issues. If the issue is found and is not of type
Vulnerability, it will pass.

If the issue is of type Vulnerability, the task will now ensure that the
component from the issue matches a component in the
releaseNotes.content.images section and that the CVE from the issue is
present in said component section.

Signed-off-by: Johnny Bieren <jbieren@redhat.com>

diff --git a/tasks/managed/embargo-check/embargo-check.yaml b/tasks/managed/embargo-check/embargo-check.yaml
--- a/tasks/managed/embargo-check/embargo-check.yaml
+++ b/tasks/managed/embargo-check/embargo-check.yaml
@@ -4,7 +4,7 @@ kind: Task
 metadata:
   name: embargo-check
   labels:
-    app.kubernetes.io/version: "0.5.0"
+    app.kubernetes.io/version: "1.0.0"
   annotations:
     tekton.dev/pipelines.minVersion: "0.12.1"
     tekton.dev/tags: release
@@ -12,7 +12,10 @@ spec:
   description: >
     Tekton task to check if any issues or CVEs in the releaseNotes key of the data.json
     are embargoed. It checks the issues by server using curl and checks the CVEs via an
-    InternalRequest. If any issue or CVE is embargoed, the task will fail.
+    InternalRequest. If any issue does not exist or any CVE is embargoed, the task will
+    fail. The task will also fail if a Jira issue listed is for a component that does
+    not exist in the releaseNotes.content.images section or if said component does not
+    list the CVE from the issue.
   params:
     - name: dataPath
       description: Path to the JSON string of the merged data to use in the data workspace
@@ -36,6 +39,12 @@ spec:
   steps:
     - name: check-issues
       image: quay.io/konflux-ci/release-service-utils:0f82be4be43294b6a96846d87ef7f7c0b9e34267
+      env:
+        - name: ACCESS_TOKEN
+          valueFrom:
+            secretKeyRef:
+              name: TODO
+              key: TODO
       script: |
         #!/usr/bin/env bash
         set -x
@@ -62,6 +71,12 @@ spec:
             exit 1
         fi
 
+        set +x # There are a lot of custom fields, don't want to pollute the logs
+        CUSTOM_RH_FIELDS="$(curl -H "Authorization: Bearer $ACCESS_TOKEN" https://issues.redhat.com/rest/api/2/field)"
+        set -x
+        CVE_FIELD="$(jq '.[] | select(.name=="CVE ID") | .id' <<< "$CUSTOM_RH_FIELDS")"
+        COMPONENT_FIELD="$(jq '.[] | select(.name=="Downstream Component Name") | .id' <<< "$CUSTOM_RH_FIELDS")"
+
         RC=0
 
         NUM_ISSUES=$(jq -cr '.releaseNotes.issues.fixed | length' "${DATA_FILE}")
@@ -69,12 +84,44 @@ spec:
             issue=$(jq -c --argjson i "$i" '.releaseNotes.issues.fixed[$i]' "${DATA_FILE}")
             server=$(jq -r '.source' <<< "$issue")
             API=$(jq -r '.[] | select(.servers[] | contains("'"$server"'")) | .api' <<< "$SUPPORTED_ISSUE_TRACKERS")
-            API_URL="https://$(jq -r '.source' <<< "$issue")/${API}/$(jq -r '.id' <<< "$issue")"
-            curl --fail --output /dev/null "${API_URL}"
+            API_URL="https://"
+            # Add authentication for issues.redhat.com
+            if [ "$server" = "issues.redhat.com" ] ; then
+                API_URL="-H \"Authorization: Bearer $ACCESS_TOKEN\" ${API_URL}"
+            fi
+            API_URL="${API_URL}$(jq -r '.source' <<< "$issue")/${API}/$(jq -r '.id' <<< "$issue")"
+            OUTPUT=$(curl --fail "${API_URL}")
             if [ $? -ne 0 ] ; then
-                echo "${issue} is not publicly visible. Assuming it is embargoed and stopping pipelineRun execution."
+                echo "${issue} is not visible. Assuming it is embargoed and stopping pipelineRun execution."
                 RC=1
             fi
+
+            # Perform additional checks only for Vulnerability issues for issues.redhat.com
+            if [ "$server" != "issues.redhat.com" ] ; then
+                continue
+            fi
+            ISSUE_TYPE=$(jq -r '.fields.issuetype.name' <<< "$OUTPUT")
+            if [ "$ISSUE_TYPE" != "Vulnerability" ] ; then
+                continue
+            fi
+            CVE_ID=$(jq -r --arg field "$CVE_FIELD" '.fields.$field' <<< "$OUTPUT")
+            COMPONENT_NAME=$(jq -r --arg field "$COMPONENT_FIELD" '.fields.$field' <<< "$OUTPUT")
+            COMPONENT_IN_RELEASE_NOTES="$(jq -ec --arg name "$COMPONENT_NAME" \
+                '.releaseNotes.content.images[] | select(.component==$name)' "$DATA_FILE")"
+            if [ $? -ne 0 ] ; then
+                echo -n "Issue $issue lists `Downstream Component Name` $COMPONENT_NAME but that does"
+                echo " not appear in releaseNotes.content.images. Failing"
+                exit 2
+            fi
+
+            if [ "$(jq --arg CVE "$CVE_ID" '.cves.fixed | has($CVE)' <<< "$COMPONENT_IN_RELEASE_NOTES")" != "true" ]
+            then
+                echo -n "Issue $issue lists `Downstream Component Name` $COMPONENT_NAME and `CVE ID` $CVE_ID"
+                echo " but that CVE is not present in the releaseNotes.content.images section for that component."
+                echo "Failing"
+                exit 3
+            fi
+            
         done
 
         exit $RC
